### ISSUE TITLE
"==" display exception!

### ISSUE THREAD

**Issue by nasoundead** [caryll/ideohint#10]
![2016-09-18 23-09-56](https://cloud.githubusercontent.com/assets/13186459/18616824/21718d8e-7df5-11e6-9ab8-aeda2b63aeb8.png)

**Comment by be5invis** [comment]
As a early issue on Iosevka, some Linux OSes will always turn on ligatures. It is a bug of FreeType or Linux' fontconfig.
Use the `term` version instead. https://github.com/be5invis/Iosevka/releases
Closed.
