### ISSUE TITLE
支持 OpenType Font Variation

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [caryll/ideohint#13]
9 月发布的 OpenType 1.8 技术规范引入了名叫 OpenType Font Variation 的新技术，被认为有益于给东亚字体做细緻的、全家族覆盖的 Hinting。如果 ideohint 能支持这个技术，一旦使用这个技术的字体普及开来（尤其是中文字体）的时候，调整字体的屏幕显示效果会游刃有余。

**Comment by be5invis** [comment]
No, it is impossible.
Theoretically impossible.
