### ISSUE TITLE
TTF versions of Noto CJK fonts, hinted with ideohint?

### ISSUE THREAD

**Issue by davelab6** [caryll/ideohint#18]
Are demo fonts showing what ideohint can do available, such as TTF versions of Noto CJK fonts that are hinted with ideohint?

**Comment by be5invis** [comment]
@davelab6 There is a [IDEOHINT template](https://github.com/caryll/ideohint-template) which is currently used to build some... internal fonts (Michael Duggan asked me to write that), and there are two small sample fonts (as well as parameters) in it.
For the TTF version of Noto/Source, I'd like to provide a building script when I have time.

**Comment by davelab6** [comment]
That would be excellent! Thank you sir :)

**Comment by be5invis** [comment]
@davelab6 I tried to use the Template to handle SHS but TTFAutohint (yes, used for Latin part) freaked out. (It says "broken table", but the TTF is built using TTX.)
The converted TTF => http://7xpe0v.com1.z0.glb.clouddn.com/SourceHanSansSC-Regular.in2.ttf

**Comment by be5invis** [comment]
OK, found the reason: SHS has 65535 glyphs which is... too many for TAH.

**Comment by davelab6** [comment]
@lemzwerg is there a ttfa limit? :)

**Comment by lemzwerg** [comment]
ttfautohint doesn't contain a tracing or error message that contains 'broken table'...

How did you call ttfautohint?  I want to reproduce the problem with this font.

**Comment by be5invis** [comment]
@lemzwerg Just simply call it, no additional parameters.
Using the GUI version can also reproduce that.

**Comment by lemzwerg** [comment]
For me it works with the current git version of ttfautohint and FreeType.  So it seems that the bug (probably in FreeType) has already been fixed.

**Comment by be5invis** [comment]
@lemzwerg I used v1.6 in your website and it failed to build.

**Comment by lemzwerg** [comment]
As mentioned earlier: It's probably a bug in FreeType.  Simply recompile from git :-)

I'll soon do a new release of ttfautohint, but updating the documentation is not an easy task: Due to the use of many new scripts not part yet of various LaTeX packages I have to patch them; similarly, I'm discovering many, many problems with the TTFs from the noto-fonts-alpha repository that I use to show the scripts...

[I'll also do a new FreeType release soon, BTW]

**Comment by be5invis** [comment]
@lemzwerg That is good.
ps. How about the process of generating VTT Talks? Everyone in M$ are waiting for that.

**Comment by lemzwerg** [comment]
no progress, sorry

**Comment by davelab6** [comment]
Can anyone at M$ waiting can put some $ to make it happen? If so, email me
:)

**Comment by be5invis** [comment]
@davelab6 I'll upload a building script that not produces TTFs. TTC building is more tricky since I removed "unused" glyphs in the Source. (Using `otfcc-ttcize` would break the 65535-glyph limit.)

**Comment by be5invis** [comment]
@lemzwerg 
I also noticed that TTFA now touches Kana (`kana`) and Kanji (`hani`)?
You can leave them into the "geometric symbol" model: no stroke identification, just align the top and bottom...

**Comment by be5invis** [comment]
@davelab6 @lemzwerg 
Here we go → https://github.com/be5invis/source-han-sans-ttf
I choose to build TTF for now.

**Comment by lemzwerg** [comment]
Mhmm, it is just a side effect that kana and kanji are affected – ttfautohint doesn't apply blue zone alignments; it only tries to align stems to the grid.  Shall I change ttfautohint to avoid this?

BTW, where can I download the resulting TTFs from your 'source-han-sans-ttf' repository?

[ttfautohint is essentially ready; you can download it temporarily from [here](http://groff.ffii.org/groff/temp/ttfautohint-1.7.tar.gz).  However, I still have difficulties with OSX and Windows binaries.  Maybe some patches are necessary – in that case I will re-tag a newer version as 1.7, so please don't distribute this file.]

**Comment by be5invis** [comment]
@lemzwerg Results are in the releases.
For Kana and Kanji you can do blue zone for only absorbing top and bottom points, and do not identify or round any inner stems.

**Comment by be5invis** [comment]
@lemzwerg 
Another solution for TTFA is that, TTFA identify glyph features (like strokes) and use IDH to calculate their final position...

**Comment by lemzwerg** [comment]
'Do not identify or round inner stems' essentially means disabling auto-hinting :-)  So I think it's easiest if I'm going to exclude kana and kanji characters.

**Comment by be5invis** [comment]
@lemzwerg 
That is acceptable either.
Kana, Kanji and Hangul can be excluded directly.

**Comment by be5invis** [comment]
@lemzwerg
Just fixed that, an instruction encoding issue. TTFs would be provided when the hints are calculated. I think maybe you can expose your instruction encoding mechanism in TAH that: we provide some "high-level" hints that follows TAH's edge-whatever mechanism, and TAH compile them into TTF...

**Comment by lemzwerg** [comment]
Sounds interesting.  What about ttfautohint's 'control instructions file' mechanism?  This could be extended to cover necessary ideohint data...

**Comment by be5invis** [comment]
@lemzwerg 
I do not think it is sufficient.

For ideographs, there are only two blue zones: "far top" and "far bottom". All strokes lie between them, and (in IDH's manner) placed to certain pixels which is close to their original position. In the VTT codegen for Microsoft I used `YIPAnchor` to set the initial positions of stems' "positioning edge", and add deltas to them to avoid collisions. The opposite ("advance") edge is linked to position edge by a `YShift`.

So for ideographs TAH should support following "high-level instructions":

- `sdYAnchor(point, cvt, pos@ppem, ...)` : Size-dependent anchoring. Anchor a point to a certain CVT with exceptions (position in pixels) for small sizes, like `sdYAnchor(point1, y880, 10@14ppem...)`.
- `sdYIPAnchor(lowPoint, pointP, highPoint, pos@ppem, ...)` : Size-dependent anchored interpolation. Point `pointP` is interpolated between `lowPoint` and `highPoint` and rounded to grid. And if the current ppem is in the exception list then the point's position is SET to that position.
- `sdYLink(refPoint, oppPoint, [low, high]@ppem, ...)` : Size-dependent linking. Link point `oppPoint` to `refPoint` without rounding, and if current ppem is in the exception list, then move the `oppPoint` to make sure that their distance does not go beyond the `[low,high]` limit for that ppem.
- Normal `YShift` and `YInterpolate`.
