### ISSUE TITLE
常见结构字面大小不统一的问题。

### ISSUE THREAD

**Issue by wdhwg001** [caryll/ideohint#19]
![screenshot](https://user-images.githubusercontent.com/8943519/30154513-bca18ac6-93ec-11e7-9fbf-57a8f2dc91e1.jpg)

在常见结构的文字中，“请”、“面”等文字的字面大小显著的低于了“至”和“授”。

虽然就单个字而言，Hinting是清晰的，但是这种字面大小的差异却会影响快速阅读的速度。

**Comment by be5invis** [comment]
这个是 inziu 调参的锅吧
反正 inziu 马上也要废掉换 Iosevka-Sarasa 了……
给你上个 NS 的图 ↓
![image](https://user-images.githubusercontent.com/240091/30154810-9cf7fcc2-93ed-11e7-9fc0-33e103b8b396.png)

**Comment by wdhwg001** [comment]
好的，那么等 Iosevka-Sarasa 发布之后我关掉这个吧。
不过，“面”和“刻”的中宫比雅黑还大，是hinting的锅还是字形的…
