### ISSUE TITLE
What does it mean for ideohinted font when run by Freetype's v40 TT interpreter?

### ISSUE THREAD

**Issue by Artoria2e5** [caryll/ideohint#9]
FreeType recently switched to [a new TT interpreter](https://www.freetype.org/freetype2/docs/subpixel-hinting.html) (v40) that looks more like DirectWrite. In contrast to Infinality's v38 subpixel interpreter which tries to do [what MS did in ClearType](https://www.microsoft.com/typography/cleartype/truetypecleartype.aspx), v40 completely ignores horizontal hinting. MS [eats deltas](https://github.com/caryll/ideohint/blob/65d3268/instructor.js#L145), FT swallows functionalities.

While the FT people claim that v40 looks fine with modern (mainly Latin) fonts that don't try to create "pixel-perfect black and white pixels", I am afraid that its widespread adoption will cause troubles to Linux users using ideohinted CJK fonts.

**Comment by be5invis** [comment]
Ideohint does **not** produce horizontal gridfits, so this change is not affected. Period.
